# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . from . import worker_service_pb2 as worker__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in worker_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub:
    """WorkerService - Main service for SDK worker communication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/cerebelum.worker.WorkerService/Register',
                request_serializer=worker__service__pb2.RegisterRequest.SerializeToString,
                response_deserializer=worker__service__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/cerebelum.worker.WorkerService/Heartbeat',
                request_serializer=worker__service__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=worker__service__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Unregister = channel.unary_unary(
                '/cerebelum.worker.WorkerService/Unregister',
                request_serializer=worker__service__pb2.UnregisterRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.PollForTask = channel.unary_unary(
                '/cerebelum.worker.WorkerService/PollForTask',
                request_serializer=worker__service__pb2.PollRequest.SerializeToString,
                response_deserializer=worker__service__pb2.Task.FromString,
                _registered_method=True)
        self.SubmitResult = channel.unary_unary(
                '/cerebelum.worker.WorkerService/SubmitResult',
                request_serializer=worker__service__pb2.TaskResult.SerializeToString,
                response_deserializer=worker__service__pb2.Ack.FromString,
                _registered_method=True)
        self.SubmitBlueprint = channel.unary_unary(
                '/cerebelum.worker.WorkerService/SubmitBlueprint',
                request_serializer=worker__service__pb2.Blueprint.SerializeToString,
                response_deserializer=worker__service__pb2.BlueprintValidation.FromString,
                _registered_method=True)
        self.ExecuteWorkflow = channel.unary_unary(
                '/cerebelum.worker.WorkerService/ExecuteWorkflow',
                request_serializer=worker__service__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=worker__service__pb2.ExecutionHandle.FromString,
                _registered_method=True)
        self.GetExecutionStatus = channel.unary_unary(
                '/cerebelum.worker.WorkerService/GetExecutionStatus',
                request_serializer=worker__service__pb2.GetExecutionStatusRequest.SerializeToString,
                response_deserializer=worker__service__pb2.ExecutionStatus.FromString,
                _registered_method=True)
        self.ListExecutions = channel.unary_unary(
                '/cerebelum.worker.WorkerService/ListExecutions',
                request_serializer=worker__service__pb2.ListExecutionsRequest.SerializeToString,
                response_deserializer=worker__service__pb2.ListExecutionsResponse.FromString,
                _registered_method=True)
        self.ResumeExecution = channel.unary_unary(
                '/cerebelum.worker.WorkerService/ResumeExecution',
                request_serializer=worker__service__pb2.ResumeExecutionRequest.SerializeToString,
                response_deserializer=worker__service__pb2.ExecutionHandle.FromString,
                _registered_method=True)


class WorkerServiceServicer:
    """WorkerService - Main service for SDK worker communication
    """

    def Register(self, request, context):
        """Worker lifecycle management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unregister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollForTask(self, request, context):
        """Task execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitBlueprint(self, request, context):
        """Workflow management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExecutionStatus(self, request, context):
        """Execution status and control (NEW)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListExecutions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=worker__service__pb2.RegisterRequest.FromString,
                    response_serializer=worker__service__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=worker__service__pb2.HeartbeatRequest.FromString,
                    response_serializer=worker__service__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Unregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Unregister,
                    request_deserializer=worker__service__pb2.UnregisterRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'PollForTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PollForTask,
                    request_deserializer=worker__service__pb2.PollRequest.FromString,
                    response_serializer=worker__service__pb2.Task.SerializeToString,
            ),
            'SubmitResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitResult,
                    request_deserializer=worker__service__pb2.TaskResult.FromString,
                    response_serializer=worker__service__pb2.Ack.SerializeToString,
            ),
            'SubmitBlueprint': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitBlueprint,
                    request_deserializer=worker__service__pb2.Blueprint.FromString,
                    response_serializer=worker__service__pb2.BlueprintValidation.SerializeToString,
            ),
            'ExecuteWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteWorkflow,
                    request_deserializer=worker__service__pb2.ExecuteRequest.FromString,
                    response_serializer=worker__service__pb2.ExecutionHandle.SerializeToString,
            ),
            'GetExecutionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExecutionStatus,
                    request_deserializer=worker__service__pb2.GetExecutionStatusRequest.FromString,
                    response_serializer=worker__service__pb2.ExecutionStatus.SerializeToString,
            ),
            'ListExecutions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExecutions,
                    request_deserializer=worker__service__pb2.ListExecutionsRequest.FromString,
                    response_serializer=worker__service__pb2.ListExecutionsResponse.SerializeToString,
            ),
            'ResumeExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeExecution,
                    request_deserializer=worker__service__pb2.ResumeExecutionRequest.FromString,
                    response_serializer=worker__service__pb2.ExecutionHandle.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cerebelum.worker.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cerebelum.worker.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService:
    """WorkerService - Main service for SDK worker communication
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cerebelum.worker.WorkerService/Register',
            worker__service__pb2.RegisterRequest.SerializeToString,
            worker__service__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cerebelum.worker.WorkerService/Heartbeat',
            worker__service__pb2.HeartbeatRequest.SerializeToString,
            worker__service__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cerebelum.worker.WorkerService/Unregister',
            worker__service__pb2.UnregisterRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollForTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cerebelum.worker.WorkerService/PollForTask',
            worker__service__pb2.PollRequest.SerializeToString,
            worker__service__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cerebelum.worker.WorkerService/SubmitResult',
            worker__service__pb2.TaskResult.SerializeToString,
            worker__service__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitBlueprint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cerebelum.worker.WorkerService/SubmitBlueprint',
            worker__service__pb2.Blueprint.SerializeToString,
            worker__service__pb2.BlueprintValidation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cerebelum.worker.WorkerService/ExecuteWorkflow',
            worker__service__pb2.ExecuteRequest.SerializeToString,
            worker__service__pb2.ExecutionHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExecutionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cerebelum.worker.WorkerService/GetExecutionStatus',
            worker__service__pb2.GetExecutionStatusRequest.SerializeToString,
            worker__service__pb2.ExecutionStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListExecutions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cerebelum.worker.WorkerService/ListExecutions',
            worker__service__pb2.ListExecutionsRequest.SerializeToString,
            worker__service__pb2.ListExecutionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cerebelum.worker.WorkerService/ResumeExecution',
            worker__service__pb2.ResumeExecutionRequest.SerializeToString,
            worker__service__pb2.ExecutionHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
